apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-config
data:
  ASPNETCORE_URLS: "http://+:5156"
  REDIS_CONNECTION: "redis:6379"
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=orchestrator;Username=postgres;Password=postgres"
  REDIS_CONSUMER_GROUP: "orchestrator-group"
