apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orchestrator.fullname" . }}-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ include "orchestrator.fullname" . }}-api
  template:
    metadata:
      labels:
        app: {{ include "orchestrator.fullname" . }}-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ include "orchestrator.fullname" . }}-config
            - secretRef:
                name: {{ include "orchestrator.fullname" . }}-secret
